# Generated by Django 4.2 on 2023-09-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D16', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
